# Generated by Django 4.2 on 2023-04-18 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_post_profile_email_post_likes_post_comment_follows_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment_comment",
            old_name="comment_id",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment_comment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="comment_likes",
            old_name="comment_id",
            new_name="comment",
        ),
        migrations.RenameField(
            model_name="comment_likes",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="follows",
            old_name="follower_id",
            new_name="follower",
        ),
        migrations.RenameField(
            model_name="follows",
            old_name="leader_id",
            new_name="leader",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post_comment",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="post_comment",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="post_likes",
            old_name="post_id",
            new_name="post",
        ),
        migrations.RenameField(
            model_name="post_likes",
            old_name="user_id",
            new_name="user",
        ),
        migrations.AlterField(
            model_name="comment_comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 17, 46, 37, 806329)
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 17, 46, 37, 806329)
            ),
        ),
        migrations.AlterField(
            model_name="post_comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 18, 17, 46, 37, 806329)
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(
                blank=True, default=None, max_length=254, unique=True
            ),
        ),
    ]
