# Generated by Django 4.2 on 2023-04-19 08:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_rename_comment_id_comment_comment_comment_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="comment_comment",
            name="UQ_Core_Comment_Comment_user_id_comment_id",
        ),
        migrations.RemoveConstraint(
            model_name="comment_likes",
            name="UQ_Core_Comment_Likes_user_id_comment_id",
        ),
        migrations.RemoveConstraint(
            model_name="post_likes",
            name="UQ_Core_Post_Likes_user_id_post_id",
        ),
        migrations.RemoveField(
            model_name="comment_comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="comment_likes",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post_comment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="post_likes",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.AddField(
            model_name="comment_comment",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="comment_likes",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="post_comment",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="post_likes",
            name="profile",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="display_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="comment_comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 19, 11, 6, 44, 657516)
            ),
        ),
        migrations.AlterField(
            model_name="follows",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="follower_id",
                to="core.profile",
            ),
        ),
        migrations.AlterField(
            model_name="follows",
            name="leader",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="leader_id",
                to="core.profile",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 19, 11, 6, 44, 656516)
            ),
        ),
        migrations.AlterField(
            model_name="post_comment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 19, 11, 6, 44, 656516)
            ),
        ),
        migrations.AddConstraint(
            model_name="comment_comment",
            constraint=models.UniqueConstraint(
                fields=("profile_id", "comment_id"),
                name="UQ_Core_Comment_Comment_profile_id_comment_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="comment_likes",
            constraint=models.UniqueConstraint(
                fields=("profile_id", "comment_id"),
                name="UQ_Core_Comment_Likes_profile_id_comment_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="post_likes",
            constraint=models.UniqueConstraint(
                fields=("profile_id", "post_id"),
                name="UQ_Core_Post_Likes_profile_id_post_id",
            ),
        ),
    ]
